/* eslint-disable prettier/prettier */
/* eslint-disable quotes */
const strings = {
  en: {
    'Update Available': 'Update Available',
    'An update is available. Click the button below to update.': 'An update is available. Click the button below to update.',
    'Update Now': 'Update Now',
    'Subtitles': 'Subtitles',
    'Unlock': 'Unlock',
    'Lock': 'Lock',
    'Hide Subtitle': 'Hide Subtitle',
    'Show Subtitle': 'Show Subtitle',
    'Quality': 'Quality',
    'error, change quality': 'error, change quality',
    'Continue Watching': 'Continue Watching',
    'Popular Movies': 'Popular Movies',
    'more': 'more',
    'Popular Series': 'Popular Series',
    'Top Rated Movies': 'Top Rated Movies',
    'Top Rated Series': 'Top Rated Series',
    'Version': 'Version',
    'Update': 'Update',
    'Download': 'Download',
    'Play': 'Play',
    'About the Developer': 'About the Developer',
    'Player Error': 'Player Error',
    'Search': 'Search',
    'error parsing qualities: ': 'error parsing qualities: ',
  },
  ar: {
    'Update Available': 'تحديث متاح',
    'An update is available. Click the button below to update.':
      'يتوفر تحديث. انقر على الزر أدناه للتحديث.',
    'Update Now': 'حدث الآن',
    'Subtitles': 'ترجمات',
    'Unlock': 'فتح',
    'Lock': 'قفل',
    'Hide Subtitle': 'إخفاء الترجمة',
    'Show Subtitle': 'إظهار الترجمة',
    'Quality': 'جودة',
    'error, change quality': 'خطأ، تغيير الجودة',
    'Continue Watching': 'استمر في المشاهدة',
    'Popular Movies': 'أفلام شعبية',
    'more': 'المزيد',
    'Popular Series': 'مسلسلات شعبية',
    'Top Rated Movies': 'أعلى الأفلام تقييماً',
    'Top Rated Series': 'أعلى المسلسلات تقييماً',
    'Version': 'الإصدار',
    'Update': 'تحديث',
    'Download': 'تحميل',
    'Play': 'تشغيل',
    'About the Developer': 'حول المطور',
    'Player Error': 'خطأ في المشغل',
    'Search': 'بحث',
    'error parsing qualities: ': 'خطأ في تحليل الجودات: ',
  },
  fr: {
    'Update Available': 'Mise à jour disponible',
    'An update is available. Click the button below to update.': 'Une mise à jour est disponible. Cliquez sur le bouton ci-dessous pour mettre à jour.',
    'Update Now': 'Mettre à jour maintenant',
    'Subtitles': 'Sous-titres',
    'Unlock': 'Déverrouiller',
    'Lock': 'Verrouiller',
    'Hide Subtitle': 'Masquer le sous-titre',
    'Show Subtitle': 'Afficher le sous-titre',
    'Quality': 'Qualité',
    'error, change quality': 'erreur, changer la qualité',
    'Continue Watching': 'Continuer à regarder',
    'Popular Movies': 'Films populaires',
    'more': 'plus',
    'Popular Series': 'Séries populaires',
    'Top Rated Movies': 'Films les mieux notés',
    'Top Rated Series': 'Séries les mieux notées',
    'Version': 'Version',
    'Update': 'Mettre à jour',
    'Download': 'Télécharger',
    'Play': 'Jouer',
    'About the Developer': 'À propos du développeur',
    'Developer: Lounis': 'Développeur : Lounis',
    'Software Version': 'Version du logiciel',
    'Version: 0.1.4': 'Version : 0.1.4',
    'Player Error': 'Erreur du lecteur',
    'Search': 'Recherche',
    'error parsing qualities: ': "erreur d'analyse des qualités : ",
  },
};


export default strings;
